import { ApolloError } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Transfer } from '../components/Transfer'
import { useGetTransfers } from '../hooks/useGetTransfers'
import { useIpfs } from '../hooks/useIpfs'
import styles from '../styles/Home.module.css'
import { GetTransfersQuery } from '../types/generated/graphql'

const Home: NextPage = () => {
  const { data, loading, error, called, handleNextPage } = useGetTransfers()

  const createTransfers = (
    loading: boolean,
    error: ApolloError | undefined,
    data: GetTransfersQuery | undefined
  ) => {
    if (loading) return <p>Loading...</p>

    if (error) return <p>Error: {error.message}</p>

    return (
      <>
        <div className={styles.cardList}>
          {data?.transfers.map((transfer, index) => {
            return (
              <Transfer
                key={transfer.id}
                index={index}
                id={transfer.id}
                from={transfer.from}
                to={transfer.to}
                tokenId={transfer.tokenId}
                image={transfer.image}
                personality={transfer.personality ?? ''}
                characteristics={transfer.characteristics ?? ''}
                catOrDogPerson={transfer.catOrDogPerson ?? ''}
                relationshipStatus={transfer.relationshipStatus ?? ''}
                idealVacation={transfer.idealVacation ?? ''}
                artisticVocation={transfer.artisticVocation ?? ''}
                workStyle={transfer.workStyle ?? ''}
              />
            )
          })}
        </div>
      </>
    )
  }

  const transfers = called ? createTransfers(loading, error, data) : null

  return (
    <div className={styles.container}>
      <Head>
        <title>Shimeshi NFT Subgraph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>transfer list</p>
        {transfers}
        <button onClick={handleNextPage} className={styles.button}>
          {data && data.transfers.length > 0 ? 'More' : 'Get Transfers'}
        </button>
      </main>
    </div>
  )
}

export default Home
